services:
  db:
    image: postgres:14.3
    ports:
      - 5432:5432
    volumes:
      - ./database/create.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
